### ISSUE TITLE
Fails to build on windows

### ISSUE THREAD

**Issue by kingdevnl** [ftk/quickjspp#15]
cmake -G "NMake Makefiles" .

nmake  .
`Scanning dependencies of target quickjs
[  2%] Building C object quickjs/CMakeFiles/quickjs.dir/quickjs.c.obj
quickjs.c
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(117): warning C4013: '__builtin_clz' undefined; assuming extern returning int
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(123): warning C4013: '__builtin_clzll' undefined; assuming extern returning int
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(129): warning C4013: '__builtin_ctz' undefined; assuming extern returning int
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(135): warning C4013: '__builtin_ctzll' undefined; assuming extern returning int
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(138): error C2061: syntax error: identifier 'packed_u64'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(138): error C2059: syntax error: ';'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(138): error C2449: found '{' at file scope (missing function header?)
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(140): error C2059: syntax error: '}'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(146): error C2061: syntax error: identifier 'packed_u16'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(146): error C2059: syntax error: ';'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(146): error C2449: found '{' at file scope (missing function header?)
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(148): error C2059: syntax error: '}'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(157): error C2037: left of 'v' specifies undefined struct/union 'packed_u64'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(157): warning C4033: 'get_i64' must return a value
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(162): error C2037: left of 'v' specifies undefined struct/union 'packed_u64'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(167): error C2037: left of 'v' specifies undefined struct/union 'packed_u32'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(167): warning C4033: 'get_u32' must return a value
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(172): error C2037: left of 'v' specifies undefined struct/union 'packed_u32'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(172): warning C4033: 'get_i32' must return a value
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(177): error C2037: left of 'v' specifies undefined struct/union 'packed_u32'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(182): error C2037: left of 'v' specifies undefined struct/union 'packed_u16'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(182): warning C4033: 'get_u16' must return a value
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(187): error C2037: left of 'v' specifies undefined struct/union 'packed_u16'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(187): warning C4033: 'get_i16' must return a value
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(192): error C2037: left of 'v' specifies undefined struct/union 'packed_u16'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(265): error C2143: syntax error: missing ')' before '('
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(265): error C2091: function returns function
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(265): error C2059: syntax error: 'constant'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(265): error C2059: syntax error: ')'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(265): error C2146: syntax error: missing ')' before identifier 'dbuf_printf'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(265): error C2061: syntax error: identifier 'dbuf_printf'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(265): error C2059: syntax error: ';'
C:\Users\user\Downloads\quickjspp\quickjs\cutils.h(265): error C2059: syntax error: '<parameter-list>'
C:\Users\user\Downloads\quickjspp\quickjs\quickjs.h(518): warning C4244: 'function': conversion from 'int64_t' to 'int32_t', possible loss of data
C:\Users\user\Downloads\quickjspp\quickjs\quickjs.h(520): warning C4244: 'function': conversion from 'int64_t' to 'double', possible loss of data
C:\Users\user\Downloads\quickjspp\quickjs\quickjs.h(663): error C2440: 'type cast': cannot convert from 'JSValue' to 'JSValue'
C:\Users\user\Downloads\quickjspp\quickjs\quickjs.h(663): warning C4033: 'JS_DupValue' must return a value
C:\Users\user\Downloads\quickjspp\quickjs\quickjs.h(672): error C2440: 'type cast': cannot convert from 'JSValue' to 'JSValue'
C:\Users\user\Downloads\quickjspp\quickjs\quickjs.h(672): warning C4033: 'JS_DupValueRT' must return a value
C:\Users\user\Downloads\quickjspp\quickjs\quickjs.c(111): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.`

**Comment by ftk** [comment]
QuickJS currently cannot be built with Visual C. You can link against QuickJS DLL that was compiled by MinGW instead: https://github.com/ftk/quickjspp/actions/runs/275120057
