### ISSUE TITLE
Windows build fails

### ISSUE THREAD

**Issue by akincifca** [ftk/quickjspp#23]
How we can build this project in Visual Studio, can you help please?

**Comment by ftk** [comment]
There are Quickjs forks that add visual studio support, also check "msvc" branch in this repo, it should work: https://github.com/ftk/quickjspp/tree/msvc

**Comment by akincifca** [comment]
I tried msvc branch, also different quickjs windows forks but could not pass these error when compiling examples

`C:\workspaces\quickjspp\quickjspp.hpp(898): error C3083: 'is_const': the symbol to the left of a '::' must be a type
C:\workspaces\quickjspp\quickjspp.hpp(1075): note: see reference to function template instantiation 'qjs::Value &qjs::Value::add<pointer-to-member(0x0)>(const char *)' being compiled
C:\workspaces\quickjspp\test\class.cpp(62): note: see reference to function template instantiation 'qjs::Context::Module::class_registrar<base_test> &qjs::Context::Module::class_registrar<base_test>::fun<pointer-to-member(0x0)>(const char *)' being compiled
C:\workspaces\quickjspp\test\class.cpp(62): note: see reference to function template instantiation 'qjs::Context::Module::class_registrar<base_test> &qjs::Context::Module::class_registrar<base_test>::fun<pointer-to-member(0x0)>(const char *)' being compiled
C:\workspaces\quickjspp\quickjspp.hpp(898): error C2039: 'value': is not a member of 'qjs::detail::get_set<pointer-to-member(0x0)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x0)>'
C:\workspaces\quickjspp\quickjspp.hpp(905): error C2065: 'value': undeclared identifier
C:\workspaces\quickjspp\quickjspp.hpp(905): error C2131: expression did not evaluate to a constant
C:\workspaces\quickjspp\quickjspp.hpp(905): note: a non-constant (sub-)expression was encountered
C:\workspaces\quickjspp\quickjspp.hpp(900): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x0)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x0)>'
C:\workspaces\quickjspp\quickjspp.hpp(905): error C2065: 'get': undeclared identifier
C:\workspaces\quickjspp\quickjspp.hpp(900): error C2672: 'qjs::Value::add_getter': no matching overloaded function found
C:\workspaces\quickjspp\quickjspp.hpp(905): error C2975: 'FGet': invalid template argument for 'qjs::Value::add_getter', expected compile-time constant expression
C:\workspaces\quickjspp\quickjspp.hpp(877): note: see declaration of 'FGet'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x0)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x0)>'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'set': is not a member of 'qjs::detail::get_set<pointer-to-member(0x0)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x0)>'
C:\workspaces\quickjspp\quickjspp.hpp(905): error C2065: 'set': undeclared identifier
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2672: 'qjs::Value::add_getter_setter': no matching overloaded function found
C:\workspaces\quickjspp\quickjspp.hpp(905): error C2975: 'FSet': invalid template argument for 'qjs::Value::add_getter_setter', expected compile-time constant expression
C:\workspaces\quickjspp\quickjspp.hpp(859): note: see declaration of 'FSet'
C:\workspaces\quickjspp\quickjspp.hpp(898): error C2039: 'value': is not a member of 'qjs::detail::get_set<pointer-to-member(0x10)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x10)>'
C:\workspaces\quickjspp\quickjspp.hpp(900): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x10)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x10)>'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x10)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x10)>'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'set': is not a member of 'qjs::detail::get_set<pointer-to-member(0x10)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x10)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): error C2039: 'value': is not a member of 'qjs::detail::get_set<pointer-to-member(0x14)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x14)>'
C:\workspaces\quickjspp\quickjspp.hpp(900): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x14)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x14)>'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x14)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x14)>'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'set': is not a member of 'qjs::detail::get_set<pointer-to-member(0x14)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x14)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): error C2039: 'value': is not a member of 'qjs::detail::get_set<pointer-to-member(0x18)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x18)>'
C:\workspaces\quickjspp\quickjspp.hpp(900): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x18)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x18)>'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x18)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x18)>'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'set': is not a member of 'qjs::detail::get_set<pointer-to-member(0x18)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x18)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): error C2039: 'value': is not a member of 'qjs::detail::get_set<pointer-to-member(0x20)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x20)>'
C:\workspaces\quickjspp\quickjspp.hpp(900): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x20)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x20)>'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x20)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x20)>'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'set': is not a member of 'qjs::detail::get_set<pointer-to-member(0x20)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x20)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): error C2039: 'value': is not a member of 'qjs::detail::get_set<pointer-to-member(0x28)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x28)>'
C:\workspaces\quickjspp\quickjspp.hpp(900): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x28)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x28)>'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'get': is not a member of 'qjs::detail::get_set<pointer-to-member(0x28)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x28)>'
C:\workspaces\quickjspp\quickjspp.hpp(904): error C2039: 'set': is not a member of 'qjs::detail::get_set<pointer-to-member(0x28)>'
C:\workspaces\quickjspp\quickjspp.hpp(898): note: see declaration of 'qjs::detail::get_set<pointer-to-member(0x28)>'
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~2\2017\COMMUN~1\VC\Tools\MSVC\1416~1.270\bin\Hostx86\x86\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.`

**Comment by ftk** [comment]
It works for me:
```
git clone --depth=1 --single-branch --branch=msvc --recursive https://github.com/ftk/quickjspp quickjsppwin
cd quickjsppwin
cmake -S . -B build
cmake  --build build
cd build
ctest .
```
```
cl /?
Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30038.1 for x64
cmake --version
cmake version 3.19.1
```
Did you compile as C++17/C++20?

**Comment by akincifca** [comment]
Yeah I checked, it compiles with vs2019.
I tried it with Visual Studio 2017 (v15.9) with v141 toolset and I got errors during build.
Maybe that version does not supported. Thanks for respond.
