### ISSUE TITLE
Native inheritance/base classes and multi inheritance

### ISSUE THREAD

**Issue by SamHellawell** [ftk/quickjspp#24]
Hey! Great library.

Is it possible currently to define a native C++ class's base/parent class? Furthermore, is it possible for that definition to include the parents base class and so on. I noticed an in-progress/todo commented function `base`, I tried to use it and it seemed to work to some extent but there are issues. The prototype properties seem to be there form the parent, but using any of those methods or properties causes an exception "ParentClass object expected"

In essence I would like to do:
```
        module.class_<Point>("Point")
                .constructor<int, int>()
                .fun<&Point::x>("x")
                .fun<&Point::y>("y")
                .fun<&Point::norm>("norm");

        module.class_<Point3D>("Point3D")
                .base<Point>()
                .constructor<int, int, int>()
                .fun<&Point3D::z>("z")
```

where
```
class Point3D : public Point { }
```

then in JS:
```
const point = new Point3D(1, 2, 3);
console.log('point xyz', point.x, point.y, point.z);
```

**Comment by projectitis** [comment]
Echo above on all points :)
* Great library!
* I'd also love it if class inheritance was supported in this way

**Comment by ftk** [comment]
Hello. The problem is that parentclass' methods expect only parentclass classid. To make inheritance work they would need to check if the id is of any of the inherited classes, which might be not very quick in some cases.
Another way is to disable the classid check, which would probably make a program crash if you pass wrong class type from JS, instead of an exception being thrown.
Here's the patch to disable the check:
```diff
--- a/quickjspp.hpp	(revision e39f505ee6eedc1e0caae046b9502dfb89daec89)
+++ b/quickjspp.hpp	(date 1628873494274)
@@ -767,7 +767,9 @@
     /// @throws exception if #v doesn't have the correct class id
     static const std::shared_ptr<T>& unwrap(JSContext * ctx, JSValueConst v)
     {
-        auto ptr = reinterpret_cast<std::shared_ptr<T> *>(JS_GetOpaque2(ctx, v, QJSClassId));
+        // auto ptr = reinterpret_cast<std::shared_ptr<T> *>(JS_GetOpaque2(ctx, v, QJSClassId));
+        // disable classid check to make parent methods work
+        auto ptr = reinterpret_cast<std::shared_ptr<T> *>(JS_GetOpaque2(ctx, v, JS_GetClassID(v)));
         if(!ptr)
             throw exception{};
         return *ptr;
@@ -1352,7 +1354,7 @@
                 return *this;
             }
 
-            /* TODO: needs casting to base class
+            /* TODO: needs casting to base class*/
             template <class B>
             class_registrar& base()
             {
@@ -1364,7 +1366,7 @@
                     throw exception{};
                 return *this;
             }
-             */
+
 
             ~class_registrar()
             {
```
Another way is to keep a flag whether a class is inherited and disable the id check in this case, but it feels kind of hacky.

**Comment by SamHellawell** [comment]
Yep that class ID check removal seems to have done it, thanks for that! I would argue that any developer should ensure the right type is always passed, but I understand thats not always easy and isnt so user friendly. Perhaps it could be a library configuration option to determine if the class id check should exist for multi-inheritance or not? For my case its game engine scripting so if it'll be slow I'd rather just disable it, for some non-performant use cases/debug mode the extra validation may be useful.

Should I keep the issue open for future reference incase you get around to solving this problem, or shall I close it?

**Comment by projectitis** [comment]
Sam, did you solve this one? I'm about to do exactly the same thing (`classNameBase.push(childObject)`) - also for game engine scripting :)

**Comment by SamHellawell** [comment]
I didn't unfortunately, although I didn't have much spare time to dive into quickjshpp/quickjs again. @ftk could fixing this be as simple as disabling class ID check like before in another place?

**Comment by projectitis** [comment]
Sam, I found [a possible solution](https://www.freelists.org/post/quickjs-devel/PATCH-allow-skipping-verification-of-class-ID-in-JS-GetOpaque). I'm about to implement this. It's the (current) last major hurdle to getting my project up and running.

**Comment by ftk** [comment]
Updated the patch in https://github.com/ftk/quickjspp/issues/24#issuecomment-898598951

**Comment by projectitis** [comment]
Thank ftk. That is perfect. Running like a charm!
