### ISSUE TITLE
Binding to a class throws an exception

### ISSUE THREAD

**Issue by projectitis** [ftk/quickjspp#26]
Hi,

I'm binding a simple c++ class (in this case called Coord), which is throwing an error.
My code is:
````
auto& module = context->addModule( "geom" );
module.class_<Coord>( "Coord" );
````
The stack trace is:
````
	find_hashed_shape_proto(JSRuntime * rt, JSObject * proto) Line 4725	C
 	JS_NewObjectProtoClass(JSContext * ctx, unsigned __int64 proto_val, unsigned int class_id) Line 4937	C
 	JS_NewObject(JSContext * ctx) Line 5034	C
 	qjs::Context::newObject() Line 1435	C++
 	qjs::Context::Module::class_registrar<derive::geom::Coord>::class_registrar(const char * name, qjs::Context::Module & module, qjs::Context & context) Line 1303	C++
 	qjs::Context::Module::class_<derive::geom::Coord>(const char * name) Line 1386	C++

````
And where I think the problem might be is that in the function (quickjs.c) -
````
JSValue JS_NewObjectProtoClass(JSContext *ctx, JSValueConst proto_val, JSClassID class_id)
````
The call to get_proto_obj is returning null (proto == null)
````
proto = get_proto_obj(proto_val);
````

Any ideas where to even start understanding why? 

:)

**Comment by ftk** [comment]
Are you using JS_NewContext2? It might be that js class "Object" isn't registered. Try to add `JS_AddIntrinsicBaseObjects(ctx);` and see if the error persists

**Comment by SamHellawell** [comment]
Shot in the dark, but perhaps its because you arent registering a constructor for that class? Try:

```
module.class_<Coord>("Coord")
  .constructor<your, types, here>();
```

**Comment by projectitis** [comment]
Thanks for the responses. Appreciated.

Ftk, I am not using any of the JS_ methods directly - just calling the quickjspp wrapper code. Where would I call JS_AddIntrinsicBaseObjects? P.s. 'Coord' does not extend any class. It basically has a private x and y property, and getters/setters for both - that's it :)

Sam, my original code had a constructor appended but is throwing the exception before even getting to that :) I removed it for clarity.

**Comment by projectitis** [comment]
I have no idea what is happening. All the arguments I am passing in to the quickjs code are being mangled and have different values inside the JS_ methods themselves. It has to be something related to how quickjs.lib was compiled, or how it is linked into my app. Example:
````
JSRuntime* rtx = JS_NewRuntime();
JSContext* ctx = JS_NewContext( rtx );

string code = "let a = 123; a--;";
JS_Eval( ctx, code.c_str(), code.length(), "<eval>", 0 );
````
Inside JS_Eval, the last argument, 0, has come through as a huge value (changes every time). In fact the values of all 5 arguments are different every time I run/debug.

**Comment by ftk** [comment]
Are you using quickjs.h from the forked quickjs? Also, depending on compile options sizeof(JSValue) can have different size which results in this strange behavior.

**Comment by projectitis** [comment]
ftk, you were right on the money.
I was compiling quickjs with the following flags: `JS_STRICT_NAN_BOXING, CONFIG_BIGNUM, CONFIG_JSX, CONFIG_STORAGE`
However, I was not defining these same flags in my application before including quickjspp.h.
I have changed it to the following, and now it is working fine:
````
#define JS_STRICT_NAN_BOXING
#define CONFIG_BIGNUM
#define CONFIG_JSX
#define CONFIG_STORAGE
#include "quickjspp.hpp"
````
Thanks so much for your help!
