### ISSUE TITLE
Binding a void* property causes wrap/unwrap linkage error

### ISSUE THREAD

**Issue by projectitis** [ftk/quickjspp#30]
Hi ftk,

I have a class with a void* (pointer to any object) property:
````
class Event {
    Event(){}
    void* target = nullptr;
}
````

When I bind this with quickjspp:
````
module.class_<Event>("Event")
			.constructor<>()
			.fun<&Event::target>("target");
````

I get `wrap` and `unwrap` linkage errors:
````
lld-link : error : undefined symbol: public: static unsigned __int64 __cdecl qjs::js_traits<void *, void>::wrap(struct JSContext *, void *)
lld-link : error : undefined symbol: public: static void * __cdecl qjs::js_traits<void *, void>::unwrap(struct JSContext *, unsigned __int64)
````

Any idea how I can fix this without being more specific about the pointer type of `target`?

**Comment by ftk** [comment]
Binding void *, as well as int * or something other than (registered class) * is not supported by default. You can define js_traits<void *> yourself to make it work though.

**Comment by projectitis** [comment]
Thanks ftk. I'll re-engineer my solution to avoid void* and work with registered classes - but thanks for the suggestion just in case I need it!
