### ISSUE TITLE
Simpler way to call js_init_module_os() 

### ISSUE THREAD

**Issue by drschwabe** [ftk/quickjspp#57]
This test calls the quickjs original C function: `js_init_module_os()` to load the os module....

https://github.com/ftk/quickjspp/blob/master/test/class.cpp

however, seems there is also a fair amount of rigaramole going on there to get that function to work with quickjspp context... 

my question is there a simpler way to import the os module?

I want to use the context outside of main()

**Comment by ftk** [comment]
What do you mean?
`js_init_module_os(context.ctx, "os");`
Also see https://github.com/ftk/quickjspp/blob/master/qjs.cpp

**Comment by drschwabe** [comment]
hey thx a ton actually your one line example there was key for helping to solve this at least for my case. 

I had previously gotten tripped up with scope and declaring new variables and pointers for the ctx object; supplying it directly as context.ctx skips the need to do the extra 'rigamarole'.  

Here is my example, not sure if its 'simpler' but it does let one re-use the same context outside of main ie- in other functions across the program.

```c++
#include "quickjspp.hpp" 
#include "quickjs/quickjs-libc.h"

qjs::Runtime runtime;
qjs::Context js(runtime);

int main() {
  try {
    js_std_init_handlers(runtime.rt);
    js_init_module_os(js.ctx, "os");
    js_init_module_os(js.ctx, "std");  
    js.eval(R"xxx(     
      import * as os from 'os'
      globalThis.os = os
    )xxx", "<import>", JS_EVAL_TYPE_MODULE);
  } catch (qjs::exception) {
    handleJsErr(js.getException()); 
  } 
}
